// Generated by CoffeeScript 1.6.2
(function() {
  var App, app, isMobile,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = (function() {
    function App(container, stereoscopic) {
      this.container = container;
      this.stereoscopic = stereoscopic != null ? stereoscopic : false;
      this.gameLoop = __bind(this.gameLoop, this);
      this.onResize = __bind(this.onResize, this);
      this.scene = new THREE.Scene();
      this.scene.fog = new THREE.FogExp2(0x000000, 0.002);
      this.initRenderer();
      this.initCamera();
      this.initControls();
      this.stereoEffect = new THREE.StereoEffect(this.renderer);
      this.addGroundToScene(this.scene);
      this.addLightToScene(this.scene);
      this.addSkydomeToScene(this.scene);
      this.gameLoop();
      window.addEventListener('resize', this.onResize, false);
      setTimeout(this.onResize, 1);
    }

    App.prototype.initRenderer = function() {
      var element;

      this.renderer = new THREE.WebGLRenderer();
      element = this.renderer.domElement;
      return this.container.appendChild(element);
    };

    App.prototype.initCamera = function() {
      this.camera = new THREE.PerspectiveCamera(90, 1, 0.001, 700);
      this.camera.position.set(0, 15, 0);
      return this.scene.add(this.camera);
    };

    App.prototype.initControls = function() {
      this.controls = new THREE.OrbitControls(this.camera, this.container);
      this.controls.rotateUp(Math.PI / 4);
      this.controls.target.set(this.camera.position.x + .1, this.camera.position.y, this.camera.position.z);
      this.controls.noZoom = true;
      this.controls.noPan = true;
      return this.controls.update();
    };

    App.prototype.onResize = function() {
      var height, width;

      width = this.container.offsetWidth;
      height = this.container.offsetHeight;
      this.camera.aspect = width / height;
      this.camera.updateProjectionMatrix();
      this.stereoEffect.setSize(width, height);
      return this.renderer.setSize(width, height);
    };

    App.prototype.addGroundToScene = function(scene) {
      var geometry, material, mesh;

      geometry = new THREE.PlaneGeometry(1000, 1000);
      material = new THREE.MeshPhongMaterial({
        color: 0xffffff,
        specular: 0xffffff,
        shininess: 20,
        shading: THREE.FlatShading,
        map: this.getGroundTexture()
      });
      if (!(material.map instanceof THREE.Texture)) {
        throw "Warning: no ground texture found!";
      }
      mesh = new THREE.Mesh(geometry, material);
      mesh.rotation.x = -Math.PI / 2;
      return scene.add(mesh);
    };

    App.prototype.addLightToScene = function(scene) {
      var light;

      light = new THREE.HemisphereLight(0x777777, 0x000000, 0.6);
      return scene.add(light);
    };

    App.prototype.addSkydomeToScene = function(scene) {
      var geometry, material, mesh;

      geometry = new THREE.SphereGeometry(600, 60, 40);
      material = new THREE.MeshBasicMaterial({
        map: this.getSkyTexture(),
        side: THREE.BackSide
      });
      mesh = new THREE.Mesh(geometry, material);
      return scene.add(mesh);
    };

    App.prototype.getGroundTexture = function() {
      var texture;

      texture = THREE.ImageUtils.loadTexture('./textures/patterns/checker.png');
      texture.wrapS = THREE.RepeatWrapping;
      texture.wrapT = THREE.RepeatWrapping;
      texture.repeat = new THREE.Vector2(50, 50);
      texture.anisotropy = this.renderer.getMaxAnisotropy();
      return texture;
    };

    App.prototype.getSkyTexture = function() {
      var texture;

      texture = THREE.ImageUtils.loadTexture('./textures/environments/milky_way.jpg');
      return texture;
    };

    App.prototype.gameLoop = function() {
      requestAnimationFrame(this.gameLoop);
      this.update();
      return this.render();
    };

    App.prototype.update = function() {};

    App.prototype.render = function() {
      if (this.stereoscopic) {
        return this.stereoEffect.render(this.scene, this.camera);
      } else {
        return this.renderer.render(this.scene, this.camera);
      }
    };

    return App;

  })();

  isMobile = function() {
    return /Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i.test(navigator.userAgent || navigator.vendor || window.opera);
  };

  app = new App(document.getElementById('threejs-container'), isMobile());

}).call(this);
